document.write("            <div class=\"nav-link-2\"><i class=\"fas fa-th fa-lg\"><\/i><\/div>");
document.write("            <div class=\"other-sites\">");
document.write("                <div>");
document.write("                    <a href=\"https:\/\/www.imooc.com\/\" target=\"_blank\"><img src=\"http:\/\/www.imooc.com\/favicon.ico\"");
document.write("                            alt=\"imooc\"> imooc<\/a>");
document.write("                    <a href=\"https:\/\/www.wibibi.com\/\" target=\"_blank\"><img src=\"https:\/\/www.wibibi.com\/favicon.ico\"");
document.write("                            alt=\"Wibibi\"> Wibibi<\/a>");
document.write("                    <a href=\"https:\/\/docs.emmet.io\/cheat-sheet\/\" target=\"_blank\"><img");
document.write("                            src=\"https:\/\/emmet.io\/-\/3755353140\/favicon.ico\" alt=\"Emmet\"> Emmet<\/a>");
document.write("                    <a href=\"https:\/\/www.runoob.com\/\" target=\"_blank\"><img");
document.write("                            src=\"https:\/\/static.runoob.com\/images\/favicon.ico\" alt=\"RUNOOB\"> RUNOOB<\/a>");
document.write("                    <a href=\"https:\/\/www.w3school.com.cn\/\" target=\"_blank\"><img");
document.write("                            src=\"https:\/\/www.w3school.com.cn\/ui2019\/logo-16-red.png\" alt=\"W3school\"> W3school<\/a>");
document.write("                    <a href=\"https:\/\/flatuicolors.com\/\" target=\"_blank\"><img");
document.write("                            src=\"https:\/\/flatuicolors.com\/static\/favicon.ico\" alt=\"flatuicolors\"> flatuicolors<\/a>");
document.write("                    <a href=\"https:\/\/developer.mozilla.org\/zh-CN\/docs\/Web\" target=\"_blank\"><img");
document.write("                            src=\"https:\/\/developer.mozilla.org\/static\/img\/favicon32.7f3da72dcea1.png\"");
document.write("                            alt=\"MDN Web Docs\"> MDN Web Docs<\/a>");
document.write("                    <a href=\"https:\/\/caniuse.com\/\" target=\"_blank\"><img src=\"https:\/\/caniuse.com\/img\/favicon-128.png\"");
document.write("                            alt=\"Can I use\"> Can I use<\/a>");
document.write("                    <a href=\"https:\/\/fontawesome.com\/\" target=\"_blank\"><img src=\"https:\/\/fontawesome.com\/images\/favicons\/favicon-16x16.png\"");
document.write("                            alt=\"Can I use\"> Font Awesome<\/a>");
document.write("                <\/div>");
document.write("            <\/div>");
