document.write( '<div class=\"nav-link\"><i class=\"fas fa-th fa-lg\"></i></div>\n' );
document.write( '            <div class=\"other-sites\">\n' );
document.write( '                <div>\n' );
document.write( '                    <a href=\"https://www.imooc.com/\" target=\"_blank\"><img src=\"http://www.imooc.com/favicon.ico\"\n' );
document.write( '                            alt=\"imooc\"> imooc</a>\n' );
document.write( '                    <a href=\"https://www.wibibi.com/\" target=\"_blank\"><img src=\"https://www.wibibi.com/favicon.ico\"\n' );
document.write( '                            alt=\"Wibibi\"> Wibibi</a>\n' );
document.write( '                    <a href=\"https://docs.emmet.io/cheat-sheet/\" target=\"_blank\"><img\n' );
document.write( '                            src=\"https://emmet.io/-/3755353140/favicon.ico\" alt=\"Emmet\"> Emmet</a>\n' );
document.write( '                    <a href=\"https://www.runoob.com/\" target=\"_blank\"><img\n' );
document.write( '                            src=\"https://static.runoob.com/images/favicon.ico\" alt=\"RUNOOB\"> RUNOOB</a>\n' );
document.write( '                    <a href=\"https://www.w3school.com.cn/\" target=\"_blank\"><img\n' );
document.write( '                            src=\"https://www.w3school.com.cn/ui2019/logo-16-red.png\" alt=\"W3school\"> W3school</a>\n' );
document.write( '                    <a href=\"https://flatuicolors.com/\" target=\"_blank\"><img\n' );
document.write( '                            src=\"https://flatuicolors.com/static/favicon.ico\" alt=\"flatuicolors\"> flatuicolors</a>\n' );
document.write( '                    <a href=\"https://developer.mozilla.org/zh-CN/docs/Web\" target=\"_blank\"><img\n' );
document.write( '                            src=\"https://developer.mozilla.org/static/img/favicon32.7f3da72dcea1.png\"\n' );
document.write( '                            alt=\"MDN Web Docs\"> MDN Web Docs</a>\n' );
document.write( '                    <a href=\"https://caniuse.com/\" target=\"_blank\"><img src=\"https://caniuse.com/img/favicon-128.png\"\n' );
document.write( '                            alt=\"Can I use\"> Can I use</a>\n' );
document.write( '                    <a href=\"https://fontawesome.com/\" target=\"_blank\"><img src=\"https://fontawesome.com/images/favicons/favicon-16x16.png\"\n' );
document.write( '                            alt=\"Can I use\"> Font Awesome</a>\n' );
document.write( '                </div>\n' );
document.write( '            </div>' );
